app:
  host: http://article.example.com
  public_list_size: 10

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:8889/articles_sql
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: DEBUG